// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AncestorCloud.Touch
{
	public partial class AncestorCloud_TouchViewController : UIViewController
	{
		public AncestorCloud_TouchViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
